apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vatbe-tls
  namespace: vatbe
spec:
  secretName: vatbe-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - vatbe.garry-ai.cloud
